'use client';
import { useState } from 'react';
import { FileDown, Loader2 } from 'lucide-react';
import { toast } from 'react-hot-toast';
import { formatCurrency } from '@/lib/mortgage';

export default function PDFExportButton({ inputs, results, allTermsResults }) {
  const [generating, setGenerating] = useState(false);

  const generatePDF = async () => {
    setGenerating(true);
    try {
      // Dynamic import to avoid SSR issues
      const jsPDF = (await import('jspdf')).default;
      const autoTable = (await import('jspdf-autotable')).default;

      const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
      const W = doc.internal.pageSize.getWidth();

      // Header
      doc.setFillColor(15, 23, 42);
      doc.rect(0, 0, W, 28, 'F');
      doc.setTextColor(99, 102, 241);
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('MortgageIQ', 14, 17);
      doc.setTextColor(148, 163, 184);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text('Professional Mortgage Analysis Report', 14, 24);
      doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`, W - 14, 24, { align: 'right' });

      // Loan summary
      doc.setTextColor(30, 41, 59);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Loan Parameters', 14, 40);

      const summaryData = [
        ['Loan Amount', formatCurrency(inputs.loanAmount), 'Down Payment', formatCurrency(inputs.downPayment)],
        ['Interest Rate', `${inputs.interestRate}%`, 'Principal', formatCurrency(inputs.loanAmount - inputs.downPayment)],
        ['Property Tax/yr', formatCurrency(inputs.propertyTaxes), 'Home Insurance/yr', formatCurrency(inputs.homeInsurance)],
        ['PMI Rate', `${inputs.pmi}%`, 'HOA Fees/mo', formatCurrency(inputs.hoaFees)],
        ['Extra Payment/mo', formatCurrency(inputs.extraMonthlyPayment), '', ''],
      ];

      autoTable(doc, {
        startY: 44,
        body: summaryData,
        theme: 'grid',
        styles: { fontSize: 9, cellPadding: 3 },
        columnStyles: {
          0: { fontStyle: 'bold', textColor: [71, 85, 105] },
          2: { fontStyle: 'bold', textColor: [71, 85, 105] },
        },
      });

      // All terms comparison
      const currentY = doc.lastAutoTable.finalY + 10;
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('All Loan Terms Comparison', 14, currentY);

      const tableData = allTermsResults.map(r => [
        `${r.term} Years`,
        formatCurrency(r.principal),
        `${inputs.interestRate}%`,
        formatCurrency(r.monthlyPayment),
        formatCurrency(r.monthlyPI),
        formatCurrency(r.totalInterest),
        formatCurrency(r.totalCost),
      ]);

      autoTable(doc, {
        startY: currentY + 4,
        head: [['Loan Term', 'Principal', 'Rate', 'Monthly (Total)', 'P&I Only', 'Total Interest', 'Total Cost']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [99, 102, 241], textColor: [255, 255, 255], fontSize: 9, fontStyle: 'bold' },
        styles: { fontSize: 9, cellPadding: 3 },
        alternateRowStyles: { fillColor: [248, 250, 252] },
      });

      // Amortization highlights (first year + every 5 years)
      if (results.schedule && results.schedule.length > 0) {
        doc.addPage();
        doc.setFillColor(15, 23, 42);
        doc.rect(0, 0, W, 14, 'F');
        doc.setTextColor(99, 102, 241);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Amortization Schedule Highlights', 14, 10);

        const schedData = results.schedule.map(s => [
          s.month,
          s.year,
          formatCurrency(s.payment),
          formatCurrency(s.principal),
          formatCurrency(s.interest),
          formatCurrency(s.balance),
          formatCurrency(s.totalInterestPaid),
        ]);

        autoTable(doc, {
          startY: 20,
          head: [['Month', 'Year', 'Payment', 'Principal', 'Interest', 'Balance', 'Cumul. Interest']],
          body: schedData,
          theme: 'striped',
          headStyles: { fillColor: [99, 102, 241], textColor: [255, 255, 255], fontSize: 8 },
          styles: { fontSize: 8, cellPadding: 2 },
        });
      }

      // Footer on all pages
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFillColor(241, 245, 249);
        doc.rect(0, doc.internal.pageSize.getHeight() - 10, W, 10, 'F');
        doc.setTextColor(148, 163, 184);
        doc.setFontSize(7);
        doc.text('Generated by MortgageIQ — For informational purposes only. Consult a financial advisor.', 14, doc.internal.pageSize.getHeight() - 4);
        doc.text(`Page ${i} of ${pageCount}`, W - 14, doc.internal.pageSize.getHeight() - 4, { align: 'right' });
      }

      doc.save(`MortgageIQ_Report_${new Date().toISOString().split('T')[0]}.pdf`);
      toast.success('PDF report generated!');
    } catch (err) {
      toast.error('PDF generation failed: ' + err.message);
      console.error(err);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <button
      onClick={generatePDF}
      disabled={generating}
      className="btn-gold flex items-center gap-2"
    >
      {generating ? (
        <Loader2 size={15} className="animate-spin" />
      ) : (
        <FileDown size={15} />
      )}
      {generating ? 'Generating PDF...' : 'Generate PDF Report'}
    </button>
  );
}
